### ISSUE TITLE
Device argument is missing

### ISSUE THREAD

**Issue by RetroVape** [ljmerza/harmony-remote-card#1]
I am getting  this error when using the buttons:

"Harmony Hub: Missing required argument: device"

When running the remote.send_command service, I get this error when nor device is listed or the formatting of the command is off.

**Comment by werfpsa** [comment]
> I am getting this error when using the buttons:
> 
> "Harmony Hub: Missing required argument: device"
> 
> When running the remote.send_command service, I get this error when nor device is listed or the formatting of the command is off.

Having the same issue.

**Comment by ljmerza** [comment]
should be fixed in v 1.4.3
