### ISSUE TITLE
[documentation] custom type reference incorrect

### ISSUE THREAD

**Issue by jeroenhe** [ljmerza/harmony-remote-card#3]
Thank you for this plugin. Even though I haven't got it working yet, I'm really looking forward to using it.

In the documentation [README](https://github.com/ljmerza/harmony-remote-card/blob/master/README.md), it says:

```
type: custom:harmony-remote-card
entity: remote.harmony_hub
```

and

```
type: custom:harmony-hub-card
entity: remote.harmony_hub
```

That's not consistent and probably one of both is incorrect?

**Comment by esackbauer** [comment]
Wow thank you, I was trying since yesterday and I didnt pay close attention when I moved over the example config and changed it.

**Comment by esackbauer** [comment]
#4
